// AUTO-GENERATED by tools/embed-templates.mjs — do not edit by hand.
// Contains the four email templates so they ship inside every serverless
// function bundle. Rerun:  node tools/embed-templates.mjs

export const TEMPLATE_HR = `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>Congratulations — Unity Software</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style>
    body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
    body { margin: 0 !important; padding: 0 !important; width: 100% !important; }
    a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }
  </style>
</head>
<body style="margin:0; padding:0; background-color:#f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <div style="display:none; font-size:1px; color:#f4f4f5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;">
    Congratulations on your achievement — from the team at Unity Software
  </div>

  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#f4f4f5;">
    <tr>
      <td align="center" style="padding: 32px 16px;">
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px; background-color:#ffffff; border-radius:16px; overflow:hidden;">

          <!-- Letterhead -->
          <tr>
            <td style="padding:0; line-height:0;">
              <img src="header.jpg" alt="Unity Software" width="600" style="display:block; width:100%; max-width:600px; height:auto;" />
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 40px 40px 24px 40px;">
              <p style="margin:0 0 8px 0; font-size:15px; line-height:1.5; color:#6b7280;">Dear {{recipient_name}},</p>
              <h1 style="margin:0 0 20px 0; font-size:26px; font-weight:700; line-height:1.25; color:#111827; letter-spacing:-0.02em;">Congratulations</h1>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                On behalf of the entire team at <strong>Unity Software</strong>, we would like to extend our warmest congratulations on your recent achievement.
              </p>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                Your dedication, professionalism, and the impact you’ve made stand out. Moments like these remind us why the logistics industry continues to move forward — through people who care deeply about excellence and continuous improvement.
              </p>
              <p style="margin:0 0 28px 0; font-size:16px; line-height:1.65; color:#374151;">
                We are proud to celebrate this milestone with you and look forward to seeing the great work that lies ahead.
              </p>
              <div style="height:3px; width:48px; background:#f59e0b; border-radius:2px; margin-bottom:28px;"></div>
              <p style="margin:0 0 4px 0; font-size:16px; line-height:1.5; color:#374151;">With warm regards,</p>
            </td>
          </tr>

          <!-- Signature -->
          <tr>
            <td style="padding: 0 40px 36px 40px;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td width="72" valign="top" style="padding-right:16px;">
                    <img src="avatar_hr.png" alt="" width="64" height="64" style="display:block; width:64px; height:64px; border-radius:50%; border:2px solid #f3f4f6;" />
                  </td>
                  <td valign="middle">
                    <p style="margin:0 0 2px 0; font-size:16px; font-weight:600; color:#111827;">Amara Njoroge</p>
                    <p style="margin:0 0 6px 0; font-size:13px; color:#6b7280; font-weight:500;">HR Manager · Unity Software</p>
                    <p style="margin:0; font-size:13px; line-height:1.5; color:#6b7280;">
                      <a href="tel:+254778903044" style="color:#6b7280; text-decoration:none;">+254 778 903 044</a><br>
                      <a href="mailto:hr@unity-software.online" style="color:#6b7280; text-decoration:none;">hr@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:0;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#111827;">
                <tr>
                  <td style="padding:28px 40px;">
                    <p style="margin:0 0 8px 0; font-size:13px; font-weight:600; color:#f9fafb; letter-spacing:0.02em;">UNITY SOFTWARE</p>
                    <p style="margin:0 0 16px 0; font-size:12px; line-height:1.5; color:#9ca3af;">Logistics excellence · Supply chain optimization</p>
                    <p style="margin:0; font-size:12px; line-height:1.6; color:#9ca3af;">
                      <a href="https://www.unity-software.online" style="color:#f59e0b; text-decoration:none;">www.unity-software.online</a>
                      &nbsp;·&nbsp;
                      <a href="mailto:hello@unity-software.online" style="color:#9ca3af; text-decoration:none;">hello@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px;">
          <tr>
            <td style="padding:24px 16px; text-align:center;">
              <p style="margin:0; font-size:11px; line-height:1.5; color:#9ca3af;">
                This message was sent by Unity Software (Liceria &amp; Co.).
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;

export const TEMPLATE_HIRING = `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>Congratulations — Unity Software</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style>
    body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
    body { margin: 0 !important; padding: 0 !important; width: 100% !important; }
    a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }
  </style>
</head>
<body style="margin:0; padding:0; background-color:#f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <div style="display:none; font-size:1px; color:#f4f4f5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;">
    Congratulations on joining the team — from Unity Software
  </div>

  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#f4f4f5;">
    <tr>
      <td align="center" style="padding: 32px 16px;">
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px; background-color:#ffffff; border-radius:16px; overflow:hidden;">

          <!-- Letterhead -->
          <tr>
            <td style="padding:0; line-height:0;">
              <img src="header.jpg" alt="Unity Software" width="600" style="display:block; width:100%; max-width:600px; height:auto;" />
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 40px 40px 24px 40px;">
              <p style="margin:0 0 8px 0; font-size:15px; line-height:1.5; color:#6b7280;">Dear {{recipient_name}},</p>
              <h1 style="margin:0 0 20px 0; font-size:26px; font-weight:700; line-height:1.25; color:#111827; letter-spacing:-0.02em;">Welcome aboard</h1>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                It is with great pleasure that we formally welcome you to <strong>Unity Software</strong>.
              </p>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                Your background and the conversations we shared left a clear impression. We are confident you will bring valuable perspective and energy to the team as we continue to strengthen supply-chain and logistics solutions for our partners.
              </p>
              <p style="margin:0 0 28px 0; font-size:16px; line-height:1.65; color:#374151;">
                We look forward to working alongside you and supporting your success from day one.
              </p>
              <div style="height:3px; width:48px; background:#f59e0b; border-radius:2px; margin-bottom:28px;"></div>
              <p style="margin:0 0 4px 0; font-size:16px; line-height:1.5; color:#374151;">Kind regards,</p>
            </td>
          </tr>

          <!-- Signature -->
          <tr>
            <td style="padding: 0 40px 36px 40px;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td width="72" valign="top" style="padding-right:16px;">
                    <img src="avatar_hiring.png" alt="" width="64" height="64" style="display:block; width:64px; height:64px; border-radius:50%; border:2px solid #f3f4f6;" />
                  </td>
                  <td valign="middle">
                    <p style="margin:0 0 2px 0; font-size:16px; font-weight:600; color:#111827;">Daniel Ochieng</p>
                    <p style="margin:0 0 6px 0; font-size:13px; color:#6b7280; font-weight:500;">Hiring Manager · Unity Software</p>
                    <p style="margin:0; font-size:13px; line-height:1.5; color:#6b7280;">
                      <a href="tel:+254778903044" style="color:#6b7280; text-decoration:none;">+254 778 903 044</a><br>
                      <a href="mailto:hiring@unity-software.online" style="color:#6b7280; text-decoration:none;">hiring@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:0;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#111827;">
                <tr>
                  <td style="padding:28px 40px;">
                    <p style="margin:0 0 8px 0; font-size:13px; font-weight:600; color:#f9fafb; letter-spacing:0.02em;">UNITY SOFTWARE</p>
                    <p style="margin:0 0 16px 0; font-size:12px; line-height:1.5; color:#9ca3af;">Logistics excellence · Supply chain optimization</p>
                    <p style="margin:0; font-size:12px; line-height:1.6; color:#9ca3af;">
                      <a href="https://www.unity-software.online" style="color:#f59e0b; text-decoration:none;">www.unity-software.online</a>
                      &nbsp;·&nbsp;
                      <a href="mailto:hello@unity-software.online" style="color:#9ca3af; text-decoration:none;">hello@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px;">
          <tr>
            <td style="padding:24px 16px; text-align:center;">
              <p style="margin:0; font-size:11px; line-height:1.5; color:#9ca3af;">
                This message was sent by Unity Software (Liceria &amp; Co.).
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;

export const TEMPLATE_DIRECTOR = `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>Congratulations — Unity Software</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style>
    body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
    body { margin: 0 !important; padding: 0 !important; width: 100% !important; }
    a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }
  </style>
</head>
<body style="margin:0; padding:0; background-color:#f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <div style="display:none; font-size:1px; color:#f4f4f5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;">
    A personal note of congratulations from the Director — Unity Software
  </div>

  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#f4f4f5;">
    <tr>
      <td align="center" style="padding: 32px 16px;">
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px; background-color:#ffffff; border-radius:16px; overflow:hidden;">

          <!-- Letterhead -->
          <tr>
            <td style="padding:0; line-height:0;">
              <img src="header.jpg" alt="Unity Software" width="600" style="display:block; width:100%; max-width:600px; height:auto;" />
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 40px 40px 24px 40px;">
              <p style="margin:0 0 8px 0; font-size:15px; line-height:1.5; color:#6b7280;">Dear {{recipient_name}},</p>
              <h1 style="margin:0 0 20px 0; font-size:26px; font-weight:700; line-height:1.25; color:#111827; letter-spacing:-0.02em;">Congratulations</h1>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                I wanted to take a moment to personally congratulate you on this well-deserved recognition.
              </p>
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;">
                The standard you set and the consistency you bring are exactly the qualities that strengthen our organisation and the partners we serve. Achievements like yours raise the bar for everyone around you.
              </p>
              <p style="margin:0 0 28px 0; font-size:16px; line-height:1.65; color:#374151;">
                Please accept my sincere appreciation. I look forward to the continued contributions you will make.
              </p>
              <div style="height:3px; width:48px; background:#f59e0b; border-radius:2px; margin-bottom:28px;"></div>
              <p style="margin:0 0 4px 0; font-size:16px; line-height:1.5; color:#374151;">With respect and appreciation,</p>
            </td>
          </tr>

          <!-- Signature -->
          <tr>
            <td style="padding: 0 40px 36px 40px;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td width="72" valign="top" style="padding-right:16px;">
                    <img src="avatar_director.png" alt="" width="64" height="64" style="display:block; width:64px; height:64px; border-radius:50%; border:2px solid #f3f4f6;" />
                  </td>
                  <td valign="middle">
                    <p style="margin:0 0 2px 0; font-size:16px; font-weight:600; color:#111827;">Grace Wambui</p>
                    <p style="margin:0 0 6px 0; font-size:13px; color:#6b7280; font-weight:500;">Director · Unity Software</p>
                    <p style="margin:0; font-size:13px; line-height:1.5; color:#6b7280;">
                      <a href="tel:+254778903044" style="color:#6b7280; text-decoration:none;">+254 778 903 044</a><br>
                      <a href="mailto:director@unity-software.online" style="color:#6b7280; text-decoration:none;">director@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:0;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#111827;">
                <tr>
                  <td style="padding:28px 40px;">
                    <p style="margin:0 0 8px 0; font-size:13px; font-weight:600; color:#f9fafb; letter-spacing:0.02em;">UNITY SOFTWARE</p>
                    <p style="margin:0 0 16px 0; font-size:12px; line-height:1.5; color:#9ca3af;">Logistics excellence · Supply chain optimization</p>
                    <p style="margin:0; font-size:12px; line-height:1.6; color:#9ca3af;">
                      <a href="https://www.unity-software.online" style="color:#f59e0b; text-decoration:none;">www.unity-software.online</a>
                      &nbsp;·&nbsp;
                      <a href="mailto:hello@unity-software.online" style="color:#9ca3af; text-decoration:none;">hello@unity-software.online</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px;">
          <tr>
            <td style="padding:24px 16px; text-align:center;">
              <p style="margin:0; font-size:11px; line-height:1.5; color:#9ca3af;">
                This message was sent by Unity Software (Liceria &amp; Co.).
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;

export const TEMPLATE_GENERIC = `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>Congratulations — Unity Software</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style>
    /* Reset */
    body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
    body { margin: 0 !important; padding: 0 !important; width: 100% !important; }
    a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }

    /* Client-specific */
    .ReadMsgBody { width: 100%; }
    .ExternalClass { width: 100%; }
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; }

    /* Typography */
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: #f4f4f5;
      color: #1a1a1a;
    }

    /* Dark mode support */
    @media (prefers-color-scheme: dark) {
      .email-bg { background-color: #0f0f0f !important; }
      .card { background-color: #1c1c1e !important; }
      .text-primary { color: #f5f5f7 !important; }
      .text-secondary { color: #a1a1a6 !important; }
      .divider { border-color: #2c2c2e !important; }
    }
  </style>
</head>
<body style="margin:0; padding:0; background-color:#f4f4f5;" class="email-bg">
  <!-- Preview text -->
  <div style="display:none; font-size:1px; color:#f4f4f5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;">
    Congratulations on your achievement — from the team at Unity Software
  </div>

  <!-- Outer wrapper -->
  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#f4f4f5;" class="email-bg">
    <tr>
      <td align="center" style="padding: 32px 16px;">

        <!-- Email container -->
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px; background-color:#ffffff; border-radius:16px; overflow:hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.06);" class="card">

          <!-- ===== HEADER / LETTERHEAD ===== -->
          <tr>
            <td style="padding:0; line-height:0;">
              <img src="header.jpg" alt="Unity Software — Liceria & Co." width="600" style="display:block; width:100%; max-width:600px; height:auto;" />
            </td>
          </tr>

          <!-- ===== BODY ===== -->
          <tr>
            <td style="padding: 40px 40px 24px 40px;">

              <!-- Greeting -->
              <p style="margin:0 0 8px 0; font-size:15px; line-height:1.5; color:#6b7280;" class="text-secondary">
                Dear {{recipient_name}},
              </p>

              <!-- Headline -->
              <h1 style="margin:0 0 20px 0; font-size:26px; font-weight:700; line-height:1.25; color:#111827; letter-spacing:-0.02em;" class="text-primary">
                Congratulations
              </h1>

              <!-- Body copy -->
              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;" class="text-primary">
                On behalf of the entire team at <strong>Unity Software</strong>, we would like to extend our warmest congratulations on your recent achievement.
              </p>

              <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65; color:#374151;" class="text-primary">
                Your dedication, professionalism, and the impact you’ve made stand out. Moments like these remind us why the logistics industry continues to move forward — through people who care deeply about excellence and continuous improvement.
              </p>

              <p style="margin:0 0 28px 0; font-size:16px; line-height:1.65; color:#374151;" class="text-primary">
                We are proud to celebrate this milestone with you and look forward to seeing the great work that lies ahead.
              </p>

              <!-- Accent line -->
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                  <td style="padding:0 0 28px 0;">
                    <div style="height:3px; width:48px; background:linear-gradient(90deg, #f59e0b, #f97316); border-radius:2px;"></div>
                  </td>
                </tr>
              </table>

              <!-- Closing -->
              <p style="margin:0 0 4px 0; font-size:16px; line-height:1.5; color:#374151;" class="text-primary">
                With warm regards,
              </p>

            </td>
          </tr>

          <!-- ===== SIGNATURE BLOCK ===== -->
          <tr>
            <td style="padding: 0 40px 36px 40px;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                  <!-- Avatar -->
                  <td width="72" valign="top" style="padding-right:16px;">
                    <img src="avatar_hr.png" alt="Sender photo" width="64" height="64" style="display:block; width:64px; height:64px; border-radius:50%; object-fit:cover; border:2px solid #f3f4f6;" />
                  </td>
                  <!-- Details -->
                  <td valign="middle">
                    <p style="margin:0 0 2px 0; font-size:16px; font-weight:600; color:#111827; letter-spacing:-0.01em;" class="text-primary">
                      {{sender_name}}
                    </p>
                    <p style="margin:0 0 6px 0; font-size:13px; color:#6b7280; font-weight:500;" class="text-secondary">
                      {{sender_title}} · Unity Software
                    </p>
                    <p style="margin:0; font-size:13px; line-height:1.5; color:#6b7280;" class="text-secondary">
                      <a href="tel:+254778903044" style="color:#6b7280; text-decoration:none;">+254 778 903 044</a><br>
                      <a href="mailto:{{sender_email}}" style="color:#6b7280; text-decoration:none;">{{sender_email}}</a>
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ===== FOOTER ===== -->
          <tr>
            <td style="padding:0;">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color:#111827;">
                <tr>
                  <td style="padding:28px 40px;">
                    <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                      <tr>
                        <td>
                          <p style="margin:0 0 8px 0; font-size:13px; font-weight:600; color:#f9fafb; letter-spacing:0.02em;">
                            UNITY SOFTWARE
                          </p>
                          <p style="margin:0 0 16px 0; font-size:12px; line-height:1.5; color:#9ca3af;">
                            Logistics excellence · Supply chain optimization
                          </p>
                          <p style="margin:0; font-size:12px; line-height:1.6; color:#9ca3af;">
                            <a href="https://www.unity-software.online" style="color:#f59e0b; text-decoration:none;">www.unity-software.online</a>
                            &nbsp;·&nbsp;
                            <a href="mailto:hello@unity-software.online" style="color:#9ca3af; text-decoration:none;">hello@unity-software.online</a>
                          </p>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

        </table>
        <!-- /Email container -->

        <!-- Legal / unsubscribe note (for transactional this can be minimal) -->
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width:600px;">
          <tr>
            <td style="padding:24px 16px; text-align:center;">
              <p style="margin:0; font-size:11px; line-height:1.5; color:#9ca3af;">
                This message was sent by Unity Software (Liceria &amp; Co.).<br>
                If you received this in error, please disregard.
              </p>
            </td>
          </tr>
        </table>

      </td>
    </tr>
  </table>
</body>
</html>
`;
